# Generated by Django 4.2.4 on 2023-09-06 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TableRelationship', '0004_alter_page_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='publish_date',
            field=models.DateField(default=datetime.date(2023, 9, 6)),
        ),
    ]
