# Generated by Django 4.2.4 on 2023-09-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('state', models.CharField(max_length=255)),
                ('is_resident', models.BooleanField()),
                ('income', models.CharField(max_length=255)),
                ('dependents', models.IntegerField()),
                ('total_savings', models.IntegerField()),
                ('total_home_loan', models.IntegerField()),
                ('credit_card_limit', models.IntegerField()),
                ('car_loan', models.IntegerField()),
                ('other_loans', models.IntegerField()),
                ('bad_credit_history', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
            ],
        ),
    ]
