# Generated by Django 4.2.4 on 2023-09-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_bookingcall_bad_credit_history_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingcall',
            name='car_loan',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bookingcall',
            name='credit_card_limit',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bookingcall',
            name='dependents',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bookingcall',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='bookingcall',
            name='other_loans',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bookingcall',
            name='total_home_loan',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bookingcall',
            name='total_savings',
            field=models.CharField(max_length=255),
        ),
    ]
