# Generated by Django 4.2.4 on 2023-09-07 09:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manyToOneRelation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish_date',
            field=models.DateField(default=datetime.date(2023, 9, 7)),
        ),
    ]
