# Generated by Django 4.2.4 on 2023-09-07 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manyToOneRelation', '0003_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='cat_or_dog',
            new_name='pages',
        ),
    ]
