# Generated by Django 4.2.4 on 2023-09-07 11:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manyToOneRelation', '0004_rename_cat_or_dog_book_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publish_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 7, 11, 46, 30, 155287, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 7, 11, 46, 30, 154234, tzinfo=datetime.timezone.utc)),
        ),
    ]
