# Generated by Django 4.2.4 on 2023-09-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=50)),
                ('service_Title', models.CharField(max_length=50)),
                ('service_des', models.TextField()),
                ('service_email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
