# Generated by Django 4.2.4 on 2023-09-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('View_practice', '0002_rename_service_des_service_des_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='age',
            field=models.IntegerField(default=18),
        ),
    ]
