# Generated by Django 4.2.4 on 2023-09-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('View_practice', '0003_service_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='fee',
            field=models.IntegerField(default=2000),
        ),
    ]
