# Generated by Django 4.2.4 on 2023-09-07 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='fees',
            new_name='fee',
        ),
    ]
